### ISSUE TITLE
pfsense 2.5.x official repo?

### ISSUE THREAD

**Issue by somedevreally** [ndejong/pfsense_fauxapi#74] opened 2020-12-16 10:55 UTC
Hello,

will this pkg be part of the pfsense 2.5 repo? any timeline?

also when trying to install manually using this script
```
set fauxapi_base_package_url='https://raw.githubusercontent.com/ndejong/pfsense_fauxapi_packages/master'
set fauxapi_latest=`fetch -qo - ${fauxapi_base_package_url}/LATEST`
fetch ${fauxapi_base_package_url}/${fauxapi_latest}
pkg-static install ${fauxapi_latest}
```
i get this error
```
fetch: /LATEST: No such file or directory
fetch.out                                       0% of 1024  B    0  Bps    00s
fetch: /: Is a directory
Usage: pkg install [-AfInFMqRUy] [-r reponame] [-Cgix] <pkg-name> ...

For more information see 'pkg help install'.
```
thanks

**Comment by ndejong** [comment] 2021-05-29 08:20
Hi - 

I'd been unable to reproduce this problem until by chance today I stumbled into your situation by chance.

The line below sometimes seems to timeout when performing a request to `githubusercontent.com` that is responsible for obtaining the `LATEST` information that points to the latest package file to download and install.
```
fauxapi_latest=`fetch -qo - ${fauxapi_base_package_url}/LATEST`
```

If this happens you'll want to check your connectivity first but if it all seems okay then you could just download the latest package file from https://github.com/ndejong/pfsense_fauxapi_packages and then manually install -
```bash
pkg-static install <package-filename>
```
Closing this for now - please feel free to re-open if you have more information etc.

**Closed by ndejong** 2021-05-29 08:20 UTC

**Comment by dunderrrrrr** [comment] 2021-05-29 08:25
No official repo news?

**Comment by bill-mcgonigle** [comment] 2023-01-17 21:06
on:
```
GNU bash, version 5.1.16(0)-release-(armv7-portbld-freebsd12.3)
12.3-STABLE
```
I need to add `export` to the two `set` lines or get the same error message.
